#!/usr/bin/env python3
"""
Platform-specific bug bounty report generator.
Produces submission-ready reports with CVSS scoring for HackerOne, Bugcrowd, Intigriti, Immunefi.
"""

import json
import math
import os
import sys
import time


# CVSS 3.1 Base Score Calculator
CVSS_METRICS = {
    "AV": {"N": 0.85, "A": 0.62, "L": 0.55, "P": 0.20},  # Attack Vector
    "AC": {"L": 0.77, "H": 0.44},  # Attack Complexity
    "PR": {  # Privileges Required (Scope Unchanged / Changed)
        "N": (0.85, 0.85), "L": (0.62, 0.68), "H": (0.27, 0.50)
    },
    "UI": {"N": 0.85, "R": 0.62},  # User Interaction
    "S": {"U": False, "C": True},  # Scope
    "C": {"H": 0.56, "L": 0.22, "N": 0.0},  # Confidentiality
    "I": {"H": 0.56, "L": 0.22, "N": 0.0},  # Integrity
    "A": {"H": 0.56, "L": 0.22, "N": 0.0},  # Availability
}


def calculate_cvss(vector_string):
    """Calculate CVSS 3.1 base score from vector string."""
    if not vector_string:
        return 0.0, "None"

    # Parse vector
    metrics = {}
    parts = vector_string.replace("CVSS:3.1/", "").split("/")
    for part in parts:
        if ":" in part:
            k, v = part.split(":", 1)
            metrics[k] = v

    try:
        av = CVSS_METRICS["AV"][metrics["AV"]]
        ac = CVSS_METRICS["AC"][metrics["AC"]]
        scope_changed = CVSS_METRICS["S"][metrics["S"]]
        pr_idx = 1 if scope_changed else 0
        pr = CVSS_METRICS["PR"][metrics["PR"]][pr_idx]
        ui = CVSS_METRICS["UI"][metrics["UI"]]
        c = CVSS_METRICS["C"][metrics["C"]]
        i = CVSS_METRICS["I"][metrics["I"]]
        a = CVSS_METRICS["A"][metrics["A"]]

        # ISS (Impact Sub-Score)
        iss = 1 - ((1 - c) * (1 - i) * (1 - a))

        if iss <= 0:
            return 0.0, "None"

        # Impact
        if not scope_changed:
            impact = 6.42 * iss
        else:
            impact = 7.52 * (iss - 0.029) - 3.25 * (iss - 0.02) ** 15

        # Exploitability
        exploitability = 8.22 * av * ac * pr * ui

        if impact <= 0:
            return 0.0, "None"

        # Base Score
        if not scope_changed:
            score = min(impact + exploitability, 10)
        else:
            score = min(1.08 * (impact + exploitability), 10)

        score = math.ceil(score * 10) / 10

        # Rating
        if score >= 9.0:
            rating = "Critical"
        elif score >= 7.0:
            rating = "High"
        elif score >= 4.0:
            rating = "Medium"
        elif score > 0:
            rating = "Low"
        else:
            rating = "None"

        return score, rating

    except (KeyError, ValueError):
        return 0.0, "Invalid vector"


def generate_report(finding, platform="hackerone"):
    """Generate a platform-specific report from finding data."""
    title = finding.get("title", "Untitled Finding")
    vuln_type = finding.get("vuln_type", "Unknown")
    severity = finding.get("severity", "medium")
    cvss_vector = finding.get("cvss_vector", "")
    description = finding.get("description", "")
    steps = finding.get("steps_to_reproduce", [])
    impact = finding.get("impact", "")
    affected_url = finding.get("affected_url", "")
    affected_param = finding.get("affected_parameter", "")
    poc_curl = finding.get("poc_curl", "")
    remediation = finding.get("remediation", "")
    evidence = finding.get("evidence", [])

    # Calculate CVSS
    score, rating = calculate_cvss(cvss_vector)

    report = f"""# {title}

## Severity
**{rating}** ({score}/10)
CVSS 3.1 Vector: `{cvss_vector}`

## Vulnerability Type
{vuln_type}

## Affected Asset
- **URL:** {affected_url}
{"- **Parameter:** " + affected_param if affected_param else ""}

## Description
{description}

## Steps to Reproduce
"""
    for i, step in enumerate(steps, 1):
        report += f"{i}. {step}\n"

    if poc_curl:
        report += f"""
## Proof of Concept

```bash
{poc_curl}
```
"""

    report += f"""
## Impact
{impact}
"""

    if remediation:
        report += f"""
## Remediation Suggestion
{remediation}
"""

    if evidence:
        report += "\n## Supporting Evidence\n"
        for ev in evidence:
            report += f"- {ev}\n"

    # Platform-specific additions
    if platform == "hackerone":
        report += f"""
---
*Report generated by bounty-hunter-toolkit on {time.strftime('%Y-%m-%d')}*
"""
    elif platform == "bugcrowd":
        # Map CVSS rating to Bugcrowd priority
        priority_map = {"Critical": "P1", "High": "P2", "Medium": "P3", "Low": "P4"}
        priority = priority_map.get(rating, "P3")
        report += f"\n**Bugcrowd Priority:** {priority}\n"
    elif platform == "immunefi":
        report += "\n**Blockchain/Contract Impact:** [Specify impact on smart contract/protocol]\n"

    return report


def load_finding(filepath):
    """Load finding data from JSON file."""
    with open(filepath) as f:
        return json.load(f)


def save_report(report, output_path):
    """Save report to file."""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(report)
    print(f"Report saved to: {output_path}")


def main():
    if len(sys.argv) < 2:
        print("Usage:")
        print("  report_generator.py <finding.json> [--platform hackerone|bugcrowd|intigriti|immunefi] [--output report.md]")
        print("  report_generator.py --cvss 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H'")
        print("  report_generator.py --template <platform>")
        sys.exit(1)

    if sys.argv[1] == "--cvss":
        vector = sys.argv[2] if len(sys.argv) > 2 else ""
        score, rating = calculate_cvss(vector)
        print(f"Score: {score}")
        print(f"Rating: {rating}")
        sys.exit(0)

    if sys.argv[1] == "--template":
        platform = sys.argv[2] if len(sys.argv) > 2 else "hackerone"
        template = {
            "title": "[Vuln Type] in [Component] allows [Impact]",
            "vuln_type": "",
            "severity": "medium",
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N",
            "description": "",
            "steps_to_reproduce": [
                "Navigate to ...",
                "Enter the following payload: ...",
                "Observe that ..."
            ],
            "impact": "",
            "affected_url": "https://example.com/endpoint",
            "affected_parameter": "param_name",
            "poc_curl": "curl -X POST https://example.com/endpoint -d 'param=payload'",
            "remediation": "",
            "evidence": []
        }
        print(json.dumps(template, indent=2))
        sys.exit(0)

    # Load finding and generate report
    finding_path = sys.argv[1]
    platform = "hackerone"
    output_path = None

    for i, arg in enumerate(sys.argv):
        if arg == "--platform" and i + 1 < len(sys.argv):
            platform = sys.argv[i + 1]
        if arg == "--output" and i + 1 < len(sys.argv):
            output_path = sys.argv[i + 1]

    finding = load_finding(finding_path)
    report = generate_report(finding, platform)

    if output_path:
        save_report(report, output_path)
    else:
        print(report)


if __name__ == "__main__":
    main()
